-- =============================================================
--  在线选课系统 数据库结构脚本（PostgreSQL 版）
--  对应《选课系统系统设计文档（优化版 V3.0）》第 5 章
--
--  与 MySQL 版的差异说明（见 README「从 MySQL 迁移到 PostgreSQL」一节）：
--   1. BIGINT AUTO_INCREMENT      -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--      （BY DEFAULT 允许种子脚本显式写入主键，导入后再校正序列）
--   2. TINYINT(1) 语义的 0/1 标志 -> SMALLINT，保持接口 JSON 中仍是 0/1 而不是 true/false
--   3. DATETIME                   -> TIMESTAMP（不带时区，与应用时区 Asia/Shanghai 一致）
--   4. ON UPDATE CURRENT_TIMESTAMP 在 PostgreSQL 中不存在，改由触发器函数 set_updated_at() 实现
--   5. 反引号 -> 无需引用（标识符统一小写，无保留字冲突）
--   6. IFNULL -> COALESCE、LIMIT ? OFFSET ? 语法一致
--   7. 唯一键用 CONSTRAINT ... UNIQUE，普通索引单独 CREATE INDEX
-- =============================================================

DROP TABLE IF EXISTS t_audit_log CASCADE;
DROP TABLE IF EXISTS t_announcement CASCADE;
DROP TABLE IF EXISTS t_notice CASCADE;
DROP TABLE IF EXISTS t_student_course_history CASCADE;
DROP TABLE IF EXISTS t_category_credit_rule CASCADE;
DROP TABLE IF EXISTS t_credit_rule CASCADE;
DROP TABLE IF EXISTS t_enroll_batch CASCADE;
DROP TABLE IF EXISTS t_waitlist CASCADE;
DROP TABLE IF EXISTS t_enrollment CASCADE;
DROP TABLE IF EXISTS t_course_schedule CASCADE;
DROP TABLE IF EXISTS t_course_offering CASCADE;
DROP TABLE IF EXISTS t_course_prereq CASCADE;
DROP TABLE IF EXISTS t_course CASCADE;
DROP TABLE IF EXISTS t_course_category CASCADE;
DROP TABLE IF EXISTS t_teacher CASCADE;
DROP TABLE IF EXISTS t_student CASCADE;
DROP TABLE IF EXISTS t_user CASCADE;
DROP TABLE IF EXISTS t_term CASCADE;

DROP FUNCTION IF EXISTS set_updated_at() CASCADE;

-- -------------------------------------------------------------
-- updated_at 自动刷新（替代 MySQL 的 ON UPDATE CURRENT_TIMESTAMP）
-- 函数体用单引号包裹而不是 $$ 美元引用：应用启动时可复用 Spring 的
-- ScriptUtils 逐句执行（它能正确处理引号与注释，但不懂美元引用）。
-- -------------------------------------------------------------
CREATE FUNCTION set_updated_at() RETURNS trigger AS '
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
' LANGUAGE plpgsql;

-- -------------------------------------------------------------
-- 1. t_term 学期
-- -------------------------------------------------------------
CREATE TABLE t_term (
  id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term_code  VARCHAR(20) NOT NULL,
  name       VARCHAR(50) NOT NULL,
  start_date DATE        NOT NULL,
  end_date   DATE        NOT NULL,
  is_current SMALLINT    NOT NULL DEFAULT 0,
  created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_term_code UNIQUE (term_code)
);
COMMENT ON TABLE t_term IS '学期';
COMMENT ON COLUMN t_term.is_current IS '是否当前学期 0否 1是';

-- -------------------------------------------------------------
-- 2. t_user 用户（认证与身份）
-- -------------------------------------------------------------
CREATE TABLE t_user (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR(50)  NOT NULL,
  password_hash VARCHAR(100) NOT NULL,
  real_name     VARCHAR(50)  NOT NULL,
  role          SMALLINT     NOT NULL,
  status        SMALLINT     NOT NULL DEFAULT 1,
  last_login_at TIMESTAMP    NULL,
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_username UNIQUE (username)
);
CREATE INDEX idx_user_role ON t_user (role);
COMMENT ON TABLE t_user IS '用户（认证与身份）';
COMMENT ON COLUMN t_user.role IS '角色 1学生 2教师 3教务管理员 4系统管理员';

-- -------------------------------------------------------------
-- 3. t_student 学生扩展信息
-- -------------------------------------------------------------
CREATE TABLE t_student (
  id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT      NOT NULL,
  student_no VARCHAR(20) NOT NULL,
  grade      VARCHAR(10) NOT NULL,
  college    VARCHAR(50) NOT NULL,
  major      VARCHAR(50) NULL,
  created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_student_user UNIQUE (user_id),
  CONSTRAINT uk_student_no   UNIQUE (student_no),
  CONSTRAINT fk_student_user FOREIGN KEY (user_id) REFERENCES t_user (id)
);
CREATE INDEX idx_student_grade ON t_student (grade);

-- -------------------------------------------------------------
-- 4. t_teacher 教师扩展信息
-- -------------------------------------------------------------
CREATE TABLE t_teacher (
  id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT      NOT NULL,
  teacher_no VARCHAR(20) NOT NULL,
  college    VARCHAR(50) NOT NULL,
  title      VARCHAR(30) NULL,
  created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_teacher_user UNIQUE (user_id),
  CONSTRAINT uk_teacher_no   UNIQUE (teacher_no),
  CONSTRAINT fk_teacher_user FOREIGN KEY (user_id) REFERENCES t_user (id)
);

-- -------------------------------------------------------------
-- 5. t_course_category 课程类别
-- -------------------------------------------------------------
CREATE TABLE t_course_category (
  id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code       VARCHAR(20) NOT NULL,
  name       VARCHAR(50) NOT NULL,
  created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_category_code UNIQUE (code)
);

-- -------------------------------------------------------------
-- 6. t_course 课程目录
-- -------------------------------------------------------------
CREATE TABLE t_course (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_code VARCHAR(20)  NOT NULL,
  name        VARCHAR(100) NOT NULL,
  category_id BIGINT       NOT NULL,
  credit      NUMERIC(4,1) NOT NULL,
  dept        VARCHAR(50)  NULL,
  description VARCHAR(500) NULL,
  status      SMALLINT     NOT NULL DEFAULT 1,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_course_code UNIQUE (course_code),
  CONSTRAINT fk_course_category FOREIGN KEY (category_id) REFERENCES t_course_category (id)
);
CREATE INDEX idx_course_name     ON t_course (name);
CREATE INDEX idx_course_category ON t_course (category_id);

-- -------------------------------------------------------------
-- 7. t_course_prereq 课程先修关系
-- -------------------------------------------------------------
CREATE TABLE t_course_prereq (
  id               BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id        BIGINT    NOT NULL,
  prereq_course_id BIGINT    NOT NULL,
  require_type     SMALLINT  NOT NULL DEFAULT 1,
  group_no         INTEGER   NOT NULL DEFAULT 1,
  created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_course_prereq UNIQUE (course_id, prereq_course_id),
  CONSTRAINT fk_prereq_course FOREIGN KEY (course_id)        REFERENCES t_course (id),
  CONSTRAINT fk_prereq_prereq FOREIGN KEY (prereq_course_id) REFERENCES t_course (id)
);
COMMENT ON COLUMN t_course_prereq.require_type IS '1与(全部满足) 2或(满足其一)';

-- -------------------------------------------------------------
-- 8. t_course_offering 学期开课
-- -------------------------------------------------------------
CREATE TABLE t_course_offering (
  id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id  BIGINT       NOT NULL,
  term_id    BIGINT       NOT NULL,
  teacher_id BIGINT       NOT NULL,
  capacity   INTEGER      NOT NULL,
  enrolled   INTEGER      NOT NULL DEFAULT 0,
  status     SMALLINT     NOT NULL DEFAULT 1,
  campus     VARCHAR(50)  NULL,
  remark     VARCHAR(200) NULL,
  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_course_term_teacher UNIQUE (course_id, term_id, teacher_id),
  CONSTRAINT ck_offering_enrolled CHECK (enrolled >= 0),
  CONSTRAINT ck_offering_capacity CHECK (capacity >= 0),
  CONSTRAINT fk_offering_course  FOREIGN KEY (course_id)  REFERENCES t_course (id),
  CONSTRAINT fk_offering_term    FOREIGN KEY (term_id)    REFERENCES t_term (id),
  CONSTRAINT fk_offering_teacher FOREIGN KEY (teacher_id) REFERENCES t_teacher (id)
);
CREATE INDEX idx_offering_term_status ON t_course_offering (term_id, status);
CREATE INDEX idx_offering_teacher     ON t_course_offering (teacher_id);
COMMENT ON TABLE t_course_offering IS '学期开课';
COMMENT ON COLUMN t_course_offering.enrolled IS '已选人数（权威计数，并发控制的唯一依据）';
COMMENT ON COLUMN t_course_offering.status IS '0停开 1开放 2已满';

-- -------------------------------------------------------------
-- 9. t_course_schedule 开课排课时段
-- -------------------------------------------------------------
CREATE TABLE t_course_schedule (
  id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offering_id  BIGINT      NOT NULL,
  weekday      SMALLINT    NOT NULL,
  start_period SMALLINT    NOT NULL,
  end_period   SMALLINT    NOT NULL,
  parity       SMALLINT    NOT NULL DEFAULT 0,
  campus       VARCHAR(50) NULL,
  building     VARCHAR(50) NULL,
  room         VARCHAR(50) NULL,
  created_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_schedule_offering FOREIGN KEY (offering_id) REFERENCES t_course_offering (id) ON DELETE CASCADE
);
CREATE INDEX idx_schedule_offering ON t_course_schedule (offering_id);
COMMENT ON COLUMN t_course_schedule.parity IS '0全周 1单周 2双周';

-- -------------------------------------------------------------
-- 10. t_enrollment 选课记录
-- -------------------------------------------------------------
CREATE TABLE t_enrollment (
  id          BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id  BIGINT    NOT NULL,
  offering_id BIGINT    NOT NULL,
  select_time TIMESTAMP NOT NULL,
  status      SMALLINT  NOT NULL DEFAULT 1,
  source      SMALLINT  NOT NULL DEFAULT 1,
  drop_time   TIMESTAMP NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_student_offering UNIQUE (student_id, offering_id),
  CONSTRAINT fk_enroll_student  FOREIGN KEY (student_id)  REFERENCES t_student (id),
  CONSTRAINT fk_enroll_offering FOREIGN KEY (offering_id) REFERENCES t_course_offering (id)
);
CREATE INDEX idx_student_status  ON t_enrollment (student_id, status);
CREATE INDEX idx_offering_status ON t_enrollment (offering_id, status);
COMMENT ON COLUMN t_enrollment.status IS '0已退 1已选';
COMMENT ON COLUMN t_enrollment.source IS '1正常选课 2候补递补';

-- -------------------------------------------------------------
-- 11. t_waitlist 候补记录
-- -------------------------------------------------------------
CREATE TABLE t_waitlist (
  id          BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id  BIGINT    NOT NULL,
  offering_id BIGINT    NOT NULL,
  queue_no    INTEGER   NOT NULL,
  join_time   TIMESTAMP NOT NULL,
  status      SMALLINT  NOT NULL DEFAULT 1,
  expire_time TIMESTAMP NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_wait_student_offering UNIQUE (student_id, offering_id),
  CONSTRAINT uk_offering_queue        UNIQUE (offering_id, queue_no),
  CONSTRAINT fk_wait_student  FOREIGN KEY (student_id)  REFERENCES t_student (id),
  CONSTRAINT fk_wait_offering FOREIGN KEY (offering_id) REFERENCES t_course_offering (id)
);
CREATE INDEX idx_waitlist_status ON t_waitlist (offering_id, status);
COMMENT ON COLUMN t_waitlist.status IS '1候补中 2已递补 3已取消 4已失效';

-- -------------------------------------------------------------
-- 12. t_enroll_batch 选课批次
-- -------------------------------------------------------------
CREATE TABLE t_enroll_batch (
  id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term_id        BIGINT       NOT NULL,
  name           VARCHAR(50)  NOT NULL,
  type           SMALLINT     NOT NULL,
  start_time     TIMESTAMP    NOT NULL,
  end_time       TIMESTAMP    NOT NULL,
  target_grade   VARCHAR(50)  NULL,
  target_college VARCHAR(100) NULL,
  priority       INTEGER      NOT NULL DEFAULT 0,
  status         SMALLINT     NOT NULL DEFAULT 1,
  created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_batch_term FOREIGN KEY (term_id) REFERENCES t_term (id)
);
CREATE INDEX idx_batch_term ON t_enroll_batch (term_id, status);
COMMENT ON COLUMN t_enroll_batch.type IS '1正常选课 2补退选';

-- -------------------------------------------------------------
-- 13. t_credit_rule 学期学分上下限
-- -------------------------------------------------------------
CREATE TABLE t_credit_rule (
  id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term_id    BIGINT       NOT NULL,
  grade      VARCHAR(10)  NOT NULL,
  min_credit NUMERIC(4,1) NOT NULL DEFAULT 0,
  max_credit NUMERIC(4,1) NOT NULL,
  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_term_grade UNIQUE (term_id, grade),
  CONSTRAINT fk_credit_term FOREIGN KEY (term_id) REFERENCES t_term (id)
);

-- -------------------------------------------------------------
-- 14. t_category_credit_rule 类别学分要求
-- -------------------------------------------------------------
CREATE TABLE t_category_credit_rule (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  term_id     BIGINT       NOT NULL,
  category_id BIGINT       NOT NULL,
  min_credit  NUMERIC(4,1) NULL,
  max_credit  NUMERIC(4,1) NULL,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_term_category UNIQUE (term_id, category_id),
  CONSTRAINT fk_ccr_term     FOREIGN KEY (term_id)     REFERENCES t_term (id),
  CONSTRAINT fk_ccr_category FOREIGN KEY (category_id) REFERENCES t_course_category (id)
);

-- -------------------------------------------------------------
-- 15. t_student_course_history 学生已修课程与成绩
-- -------------------------------------------------------------
CREATE TABLE t_student_course_history (
  id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT       NOT NULL,
  course_id  BIGINT       NOT NULL,
  term_id    BIGINT       NULL,
  score      NUMERIC(5,1) NULL,
  is_passed  SMALLINT     NOT NULL DEFAULT 0,
  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_student_course UNIQUE (student_id, course_id),
  CONSTRAINT fk_history_student FOREIGN KEY (student_id) REFERENCES t_student (id),
  CONSTRAINT fk_history_course  FOREIGN KEY (course_id)  REFERENCES t_course (id)
);
CREATE INDEX idx_history_student ON t_student_course_history (student_id);

-- -------------------------------------------------------------
-- 16. t_notice 个人通知
-- -------------------------------------------------------------
CREATE TABLE t_notice (
  id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT       NOT NULL,
  type       SMALLINT     NOT NULL,
  title      VARCHAR(100) NOT NULL,
  content    VARCHAR(500) NOT NULL,
  related_id BIGINT       NULL,
  is_read    SMALLINT     NOT NULL DEFAULT 0,
  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_notice_user FOREIGN KEY (user_id) REFERENCES t_user (id)
);
CREATE INDEX idx_notice_user ON t_notice (user_id, is_read);
COMMENT ON COLUMN t_notice.type IS '1选课结果 2候补递补 3递补失败 4退课 5公告';

-- -------------------------------------------------------------
-- 17. t_announcement 公告
-- -------------------------------------------------------------
CREATE TABLE t_announcement (
  id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publisher_id BIGINT       NOT NULL,
  title        VARCHAR(100) NOT NULL,
  content      TEXT         NOT NULL,
  target_scope VARCHAR(100) NULL,
  publish_time TIMESTAMP    NOT NULL,
  status       SMALLINT     NOT NULL DEFAULT 1,
  created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_announce_publisher FOREIGN KEY (publisher_id) REFERENCES t_user (id)
);
CREATE INDEX idx_announce_status ON t_announcement (status, publish_time);

-- -------------------------------------------------------------
-- 18. t_audit_log 审计日志
-- -------------------------------------------------------------
CREATE TABLE t_audit_log (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT       NULL,
  username    VARCHAR(50)  NULL,
  action      VARCHAR(50)  NOT NULL,
  target_type VARCHAR(30)  NULL,
  target_id   BIGINT       NULL,
  ip          VARCHAR(45)  NULL,
  result      SMALLINT     NOT NULL,
  detail      VARCHAR(500) NULL,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_user_time ON t_audit_log (user_id, created_at);
CREATE INDEX idx_audit_action    ON t_audit_log (action);
CREATE INDEX idx_audit_time      ON t_audit_log (created_at);

-- -------------------------------------------------------------
-- 为所有带 updated_at 的表挂上自动刷新触发器（替代 MySQL 的 ON UPDATE CURRENT_TIMESTAMP）
-- 说明：这里逐表显式声明，而不用 DO $$ ... $$ 循环动态生成——
-- 一是导入脚本（DbInitializer / psql）对语句分割的处理更简单，
-- 二是评审时能一眼看清到底有多少张表被覆盖。
-- -------------------------------------------------------------
CREATE TRIGGER trg_term_updated                 BEFORE UPDATE ON t_term                 FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_user_updated                 BEFORE UPDATE ON t_user                 FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_student_updated              BEFORE UPDATE ON t_student              FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_teacher_updated              BEFORE UPDATE ON t_teacher              FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_course_category_updated      BEFORE UPDATE ON t_course_category      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_course_updated               BEFORE UPDATE ON t_course               FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_course_prereq_updated        BEFORE UPDATE ON t_course_prereq        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_course_offering_updated      BEFORE UPDATE ON t_course_offering      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_course_schedule_updated      BEFORE UPDATE ON t_course_schedule      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_enrollment_updated           BEFORE UPDATE ON t_enrollment           FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_waitlist_updated             BEFORE UPDATE ON t_waitlist             FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_enroll_batch_updated         BEFORE UPDATE ON t_enroll_batch         FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_credit_rule_updated          BEFORE UPDATE ON t_credit_rule          FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_category_credit_rule_updated BEFORE UPDATE ON t_category_credit_rule FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_student_course_history_updated BEFORE UPDATE ON t_student_course_history FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_notice_updated               BEFORE UPDATE ON t_notice               FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_announcement_updated         BEFORE UPDATE ON t_announcement         FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_audit_log_updated            BEFORE UPDATE ON t_audit_log            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
